#!/bin/sh
# Build the single Auto-LAMMPS desktop entry (.app) for this Mac.
#
# usage:
#   scripts/build_desktop_app.sh --config <current.json> [--scripts-dir DIR]
#                                [--dest DIR]... [--name NAME] [--python PYTHON]
#
# The built bundle runs scripts/desktop_supervisor.py with the interpreter and private launch
# configuration named here: one click starts (or reuses) the local service and opens the page,
# and the service continues after the page closes. Nothing secret is embedded: only the resolved
# paths of the interpreter, the configuration file and the launcher/stopper scripts.
#
# --config has no default on purpose: the private launch configuration must never be baked into
# the repository. --dest defaults to $HOME/Desktop and may be repeated (for example $HOME/Applications).
set -eu

usage() {
  sed -n '2,13p' "$0" | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

scripts_dir=$(cd "$(dirname "$0")" && pwd)
name=Auto-LAMMPS
config=
python=
destinations=

while [ $# -gt 0 ]; do
  case "$1" in
    --config) config=${2:?--config 需要一个路径}; shift 2 ;;
    --scripts-dir) scripts_dir=${2:?--scripts-dir 需要一个目录}; shift 2 ;;
    --dest) destinations="$destinations ${2:?--dest 需要一个目录}"; shift 2 ;;
    --name) name=${2:?--name 需要一个名称}; shift 2 ;;
    --python) python=${2:?--python 需要一个解释器路径}; shift 2 ;;
    -h|--help) usage 0 ;;
    *) echo "未知参数：$1" >&2; usage 1 ;;
  esac
done

[ -n "$config" ] || { echo "缺少 --config：本入口需要私有的启动配置（不写入仓库）。" >&2; usage 1; }
config=$(cd "$(dirname "$config")" && pwd)/$(basename "$config")
scripts_dir=$(cd "$scripts_dir" && pwd)
[ -f "$config" ] || { echo "启动配置不存在：$config" >&2; exit 1; }
[ -f "$scripts_dir/desktop_supervisor.py" ] || { echo "缺少监督脚本：$scripts_dir/desktop_supervisor.py" >&2; exit 1; }
[ -f "$scripts_dir/stop_local.py" ] || { echo "缺少身份校验停止脚本：$scripts_dir/stop_local.py" >&2; exit 1; }
[ -f "$scripts_dir/launch_local.py" ] || { echo "缺少启动脚本：$scripts_dir/launch_local.py" >&2; exit 1; }

read_config_value() {
  if command -v plutil >/dev/null 2>&1 && plutil -extract "$1" raw -o - "$config" >/dev/null 2>&1; then
    plutil -extract "$1" raw -o - "$config"
  else
    python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))[sys.argv[2]])' "$config" "$1"
  fi
}

python=${python:-$(read_config_value python)}
state=$(read_config_value state_directory)
[ -x "$python" ] || { echo "解释器不可执行：$python" >&2; exit 1; }
[ -n "$state" ] || { echo "启动配置缺少 state_directory。" >&2; exit 1; }

[ -n "$destinations" ] || destinations=" $HOME/Desktop"

for destination in $destinations; do
  destination=$(cd "$(dirname "$destination")" 2>/dev/null && pwd)/$(basename "$destination")
  [ -d "$destination" ] || { echo "目标目录不存在：$destination" >&2; exit 1; }
  bundle="$destination/$name.app"
  rm -rf "$bundle"
  mkdir -p "$bundle/Contents/MacOS" "$bundle/Contents/Resources"
  cat > "$bundle/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>$name</string>
  <key>CFBundleDisplayName</key><string>$name</string>
  <key>CFBundleIdentifier</key><string>org.auto-lammps.launcher</string>
  <key>CFBundleVersion</key><string>3.0</string>
  <key>CFBundleShortVersionString</key><string>3.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>$name</string>
  <key>LSMinimumSystemVersion</key><string>12.0</string>
  <key>NSHighResolutionCapable</key><true/>
</dict></plist>
PLIST
  cat > "$bundle/Contents/MacOS/$name" <<ENTRY
#!/bin/zsh
# Generated by scripts/build_desktop_app.sh - the single Auto-LAMMPS local entry.
# One click: start (or reuse) the configured service and open the page. The background service
# keeps following research after the page or entry closes. Stop it separately when needed.
export SSL_CERT_FILE=/etc/ssl/cert.pem   # macOS system root store; certificate verification stays on
CONFIG="$config"
SCRIPTS="$scripts_dir"
PY="$python"
# 该 Python 是通用二进制，但部分扩展（如 pydantic_core）只编译了 arm64。
# 若入口在 Rosetta(x86_64) 下被启动，导入这些扩展会 dlopen 失败、应用打不开。
# 因此显式要求原生 arm64；不支持时（Intel 机器）自动退回直接运行。
run_py() {
  if [ "$(uname -m)" = "arm64" ]; then
    arch -arm64 "\$PY" "\$@"
  else
    "\$PY" "\$@"
  fi
}
STATE="$state"
LOG="\$STATE/desktop-entry.log"
mkdir -p "\$STATE" 2>/dev/null
if [ ! -x "\$PY" ]; then
  osascript -e 'display alert "Auto-LAMMPS 无法启动" message "找不到已安装的运行环境，请先恢复本地部署。" as critical' >/dev/null 2>&1
  exit 1
fi
if [ ! -f "\$SCRIPTS/desktop_supervisor.py" ] || [ ! -f "\$SCRIPTS/stop_local.py" ] || [ ! -f "\$CONFIG" ]; then
  osascript -e 'display alert "Auto-LAMMPS 无法启动" message "缺少本入口需要的启动、停止脚本或私有配置。" as critical' >/dev/null 2>&1
  exit 1
fi
finish() {
  code=\$?
  # A supervisor crash must not kill active research workers. Keep the service and report
  # that the entry itself failed; the next launch reuses the identity-checked service.
  if [ "\$code" -ge 4 ]; then
    osascript -e 'display alert "Auto-LAMMPS 入口异常退出" message "本地后台服务保留；重新打开应用可恢复页面并查看任务。详见运行记录中的 desktop-entry.log。" giving up after 45' >/dev/null 2>&1 &
  fi
  return 0
}
trap 'finish' EXIT
run_py -I "\$SCRIPTS/desktop_supervisor.py" --config "\$CONFIG" >>"\$LOG" 2>&1 &
child=\$!
# Cmd+Q / 注销时把信号交给监督进程；本地服务仍继续处理已登记的后台工作。
forward() { kill -TERM "\$child" 2>/dev/null; }
trap 'forward' TERM INT HUP
code=0
tries=0
while :; do
  wait "\$child"; code=\$?
  kill -0 "\$child" 2>/dev/null || break
  tries=\$((tries+1))
  if [ "\$tries" -ge 40 ]; then kill -KILL "\$child" 2>/dev/null; code=137; break; fi
  sleep 0.5
done
exit "\$code"
ENTRY
  chmod 755 "$bundle/Contents/MacOS/$name"
  cat > "$bundle/Contents/Resources/entry.json" <<RECEIPT
{
  "entry": "single",
  "name": "$name",
  "config": "$config",
  "scripts": "$scripts_dir",
  "python": "$python",
  "state_directory": "$state",
  "built_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
RECEIPT
  echo "已构建：$bundle"
done
